categories = [
    "Billing",
    "Technical Support",
    "Product Inquiry",
    "Account/Login Issues",
    "Return/Exchange",
    "Feedback/Suggestions",
]

sample_message = {
    "Billing" : [
        "I was charged twice for my order",
        "Why is there an extra fee on my bill",
        "Please ref my payment,It was taken by mistake",
        "I was charged twice for the same order, Please fix this",
        "Why did you deduct money from our account without my permission",
        "I did not receive a receipt but my card was charged.",
        "The bill is incorrect — I never subscribed to this plan.",
        "My refund has not been processed yet.",
        "You promised a discount, but I was charged full price.",
        "Can I get an invoice for my last three transactions?",
        "I canceled my subscription but was still billed.",
        "There is a mysterious fee in my statement. What is it?",
        "I was supposed to be on a free trial — why am I being charged?",
        "Please help me update my payment method.",
        "I want to request a refund for my last purchase.",
        "The payment failed but money was debited from my account.",
        "Can you explain the taxes applied to my invoice?",
        "My account was suspended even though I paid.",
        "I returned the product 3 weeks ago, but my refund hasnt been processed.",
        "The tracking shows the return was delivered, but I havent gotten my money back.",
        "Your support team said the refund was issued, but its not in my bank account.",
        "Only half the amount was refunded ,why?",
        "You deducted shipping fees despite your policy saying free returns.",
        "Your website says 30-day returns, but I was denied a refund after 25 days.",
        "I wasnt informed about non-refundable fees until after purchase.",
        "The fine print contradicts your advertised refund guarantee.",
        "The return label you provided didnt work, and now Im being charged.",
        "Customer service keeps asking for more proof even after I sent everything.",
        "Your system wont let me initiate a return,it says 'ineligible' without explanation.",
        "You denied my refund claiming no issue found, but the product doesnt work.",
        "The replacement was also faulty, and now you wont refund me.",
        "I was told to contact the manufacturer instead of getting a direct refund.",
    ],
    
    "Technical Support":[
        "The app crashes when I try to open it.",
        "My device is not responding.",
        "I can't connect to WiFi through your product.",
        "The app freezes every time I click on the settings menu.",
        "After the latest update, the app wont open at all.",
        "The app keeps crashing when I try to log in.",
        "The touchscreen isnt working after the latest firmware update.",
        "The screen is frozen, and I cant restart the device.",
        "My device is stuck on the loading screen and wont turn off.",
        "Apps crash frequently.",
        
    ],
    
    "Account/Login Issues" : [
    "I can't log into my account. It says my credentials are incorrect.",
    "I forgot my password and the reset link isn't working.",
    "My account has been locked after multiple failed attempts.",
    "I'm not receiving the verification email to sign in.",
    "Every time I try to log in, the page just refreshes and nothing happens.",
    "I registered an account, but I can't access it. Says user not found.",
    "I'm trying to change my password but getting an error message.",
    "I think someone else has accessed my account.",
    "My two-factor authentication isn't working — I'm locked out.",
    "I created an account with Google login, but now it doesn't let me in.",
    ],

    "Product Inquiry": [
        "could you please provide me information about ",
        "What is the price of ",
        "I'm looking for information on ",
        "I'm interested in ",
        "I would like to request ",
        "I'm wondering if you could tell me about ",
        "Is this size available?",
        "Is this produce available?",
        "Do you still have this product",
        "How long does ot take to ship",
        "Will it come on time",
        "why is this not available",
    ],
    
    "FeedBack/Suggestion":[
        "This is the best [product] I've ever used—worth every penny!",
        "The battery life exceeded my expectations. 10/10!",
        "Setup was effortless, and it works flawlessly.",
        "The support team resolved my issue in under 10 minutes—impressive!",
        "I received a replacement before I even returned the faulty unit. Amazing service!",
        "The agent went above and beyond to help me. Loyal customer now!",
        "The design is so sleek and user-friendly. Perfect for my needs.",
        "Regular updates keep improving functionality. Love the commitment!",
        "Offer faster shipping options at checkout.",
        "Your live chat support should be available 24/7.",
        "The return process took too long—streamline it." ,
    ],
    "Return/Exchange":[
        "I'd like to return the item I received yesterday.",
        "The product is damaged — I want a replacement.",
        "Can you help me exchange this for a different size?",
        "I received the wrong item in my order.",
        "I'm not satisfied with the product and want to return it.",
        "How do I initiate a return or get a refund?",
        "The color I received is different from what I ordered. Can I exchange it?",
        "I returned the item but haven't received a confirmation yet.",
        "The return window is still open, but your system won't let me process it.",
        "I need to return multiple items from my order — what's the process?",
    ],

    
}


category_to_department = {
    "Billing": "billing@maxVer.com",
    "Technical Support": "technical@maxVer.com",
    "Product Inquiry": "product@maxVer.com",
    "Account/Login Issues": "account@maxVer.com",
    "Refund": "Refund@maxVer.com",
    "Return/Exchange": "Return@maxVer.com",
    "Feedback/Suggestions": "feedback@maxVer.com"
}